### ISSUE TITLE
can anybody explain why JubJubExtended needed?

### ISSUE THREAD

**Issue by DreamWuGit** [dusk-network/jubjub#84]
JubJubExtended looks confusing , any help on understanding this or some tutorial doc about this ?

thanks in Advance !

**Comment by CPerezz** [comment]
It exists so that if there are any operations that need to be done between points. Sometimes is faster to use complete formulas. And these are faster when you work on Extended Coordinates.

That doesn't mean that you want to do each op in these cords.  Indeed you might not want to. But is usually the fastest way to do so (if we don't count conversions).
